---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-imageprovider
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-demo-imageprovider
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
